trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'poorvadcacr'
    repository: 'myappimg'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'acrserviceconnection'
    appName: 'poorvaapp'
    containers: 'poorvadcacr.azurecr.io/maappimg:latest'
