trigger:
- main  # Adjust if using a different branch
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ACR_NAME: 'poorvadcacr'
  IMAGE_NAME: 'myappimg'
  IMAGE_TAG: 'latest'
  RESOURCE_GROUP: 'Poorva'  # Update with your actual resource group
  WEB_APP_NAME: 'poorvaapp'  # Update with your actual Web App name
  AZURE_SERVICE_CONNECTION: 'acrserviceconnection'  # Name of your ARM service connection
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Adjust Node.js version if needed
  displayName: 'Install Node.js'
 
- script: |
    cd "ToDoList App"
    npm install
  displayName: 'Install Dependencies'
 
- task: AzureCLI@2
  displayName: 'Login to Azure and Build & Push Docker Image'
  inputs:
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(ACR_NAME)
      az acr build --registry $(ACR_NAME) --image $(IMAGE_NAME):$(IMAGE_TAG) "ToDoList App/"
 
- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
    appName: '$(WEB_APP_NAME)'
    containers: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)'